@server = https://texai-crispy-enigma-j4q5xwg7735p95-8080.preview.app.github.dev
@emp = {{server}}/api/instrumentos
###
GET {{emp}}
###
POST {{emp}}
Content-Type: application/json

{
    "nombre": "Quena",
    "categoria": "Viento",
    "description": "Tubo de madera con orificio"
}